app = "app"
primary_region = "syd"
swap_size_mb = 256

[processes]
app = "bun run start"

[deploy]
release_command = "bunx keystone prisma migrate deploy"

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = "suspend"
auto_start_machines = true
min_machines_running = 1
processes = ["app"]

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 256
