app = "nextks"
primary_region = "syd"
swap_size_mb = 256

[processes]
app = "bun start"

[build.args]
DB_PROVIDER = "postgresql"

[deploy]
release_command = "bun keystone prisma migrate deploy"

[http_service]
internal_port = 4000
force_https = true
auto_stop_machines = "suspend"
auto_start_machines = true
min_machines_running = 1
processes = ["app"]

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 256
